### ISSUE TITLE
PUBLIC key Issues

### ISSUE THREAD

**Issue by patelmiteshn** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#12]
While running the dnn inference package on X86, ubuntu 20.04 I get the public key not available error. Error pasted below. 

"W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64  InRelease' is not signed. "

How to mitigate this ?

**Comment by hemalshahNV** [comment]
The NVIDIA gpg key was invalidated recently which is causing this. You can follow either path here to resolve: https://developer.nvidia.com/blog/updating-the-cuda-linux-gpg-repository-key/


________________________________
From: Mitesh Patel ***@***.***>
Sent: Monday, May 2, 2022 11:06 PM
To: NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference] PUBLIC key Issues (Issue #12)


While running the dnn inference package on X86, ubuntu 20.04 I get the public key not available error. Error pasted below.

"W: GPG error: https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY A4B469963BF863CC
E: The repository 'https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 InRelease' is not signed. "

How to mitigate this ?
