### ISSUE TITLE
Possible to change encoder output format?

### ISSUE THREAD

**Issue by TomGrimwood** [NVIDIA-ISAAC-ROS/isaac_ros_dnn_inference#34]
I am using the Triton inference node to run a tensorflow saved model.

It receives an input type of UINT8
```yaml
input [
  {
    name: "input_tensor"
    data_type: TYPE_UINT8
    dims:[ 1, -1, -1, 3 ]
  }
]
```

Is it possible for the encoder node to pass on a Tensor of data_type: 1  (uint8) instead of the output such as below?
Or Is this perhaps a node I need to make myself.

```html
header:
  stamp:
    sec: 1683796795
    nanosec: 601918396
  frame_id: camera
tensors:
- name: input_tensor
  shape:
    rank: 4
    dims:
    - 1
    - 3
    - 512
    - 512
  data_type: 9
  strides:
  - 3145728
  - 1048576
  - 2048
  - 4
  data:
  - 225
  - 205
  - 206
  - 190
  - 225
 ...

**Comment by hemalshahNV** [comment]
Isaac ROS DNN Image Encoder only outputs normalized images as float32 for inference. Normalized images with DNNs are generally preferable because they do not let the magnitude of the input values bloat the absolute value of the weights during training.

The EfficientDet D0 model does in fact seem to expect a float32 image of shape [1, height, width, 3] containing the *normalized* input image (see [here](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tf2.md)). You should be able to use isaac_ros_dnn_image_encoder directly or you could implement your own. 

If you do, note that you'll want to use data_type: 2 for uint8 (the comment in Tensor.msg has signed and unsigned types swapped, will hotfix out correction shortly).

**Comment by TomGrimwood** [comment]
Thanks, I'm trying to use a custom model with some constraints but will try get the model in a f32 form. Thanks for the info re: uint8. I am now interested to see how that effects the model outputs, as it was working fine without.

Thanks for your help!
